repos:
  - repo: https://github.com/Quantco/pre-commit-mirrors-flake8
    rev: ''  # Use the sha / tag you want to point at
    hooks:
      - id: flake8-conda
  - repo: https://github.com/Quantco/pre-commit-mirrors-black
    rev: ''  # Use the sha / tag you want to point at
    hooks:
      - id: black-conda
  - repo: local
    hooks:
      - id: save-conda-env
        name: save-conda-env
        entry: /bin/bash ./save_env.sh
        language: script
        pass_filenames: false
  - repo: https://github.com/aflc/pre-commit-jupyter
    rev: v1.0.0
    hooks:
      - id: jupyter-notebook-cleanup
        args:
          - --remove-kernel-metadata
  - repo: https://github.com/Quantco/pre-commit-mirrors-isort
    rev: ''  # Use the sha / tag you want to point at
    hooks:
      - id: isort-conda
        args:
          - -w88
          - -tc
          - -up
          - -m3
          - -fgw0