version: '3.5'

services:
  db:
    image: postgres
    restart: always
    shm_size: '4gb'
    environment:
      POSTGRES_USER: wheretolive
      POSTGRES_PASSWORD: wheretolive
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports: # This is to run the container locally
      - 5432:5432
    networks:
      - db-network

  backend:
    image: wheretolive-backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    entrypoint: gunicorn --workers 4 --bind 0.0.0.0:5000 backend.app:create_app()
    environment: 
      DB_CONN: "postgresql://wheretolive:wheretolive@db:5432/wheretolive"
      LOGLEVEL: "INFO"
      VIRTUAL_HOST: backend.wheretolive.${TLD}
      LETSENCRYPT_HOST: backend.wheretolive.${TLD}
      VIRTUAL_PORT: 5000
    ports: # This is to run the container locally
      - 5000:5000
    networks:
      - base-network
      - db-network
    depends_on:
      - db

  frontend:
    image: wheretolive-frontend
    build:
      context: .
      dockerfile: frontend.Dockerfile
      args:
        BACKEND_HOST: ${BACKEND_HOST}
        BACKEND_PORT: ${BACKEND_PORT}
        BACKEND_PROTOCOL: ${BACKEND_PROTOCOL}
    environment:
      VIRTUAL_HOST: wheretolive.${TLD}
      LETSENCRYPT_HOST: wheretolive.${TLD}
      VIRTUAL_PORT: 80
    ports: # This is to run the container locally
      - 3000:80
    networks: 
      - base-network
    depends_on:
      - backend

networks:
  base-network:
    external: true
  db-network:
    name: db-network