version: '3.1'

services:
  db:
    image: postgres
    container_name: wheretolive-db
    restart: always
    shm_size: '4gb'
    environment:
      POSTGRES_USER: wheretolive
      POSTGRES_PASSWORD: wheretolive
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    image: wheretolive-backend
    container_name: wheretolive-backend
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: backend.Dockerfile
    entrypoint: gunicorn --workers 4 --bind 0.0.0.0:5000 backend.app:create_app()
    environment: 
      DB_CONN: "postgresql://wheretolive:wheretolive@db:5432/wheretolive"
      LOGLEVEL: "INFO"

  frontend:
    image: wheretolive-frontend
    container_name: wheretolive-frontend
    ports:
      - 3000:80
    build:
      context: .
      dockerfile: frontend.Dockerfile